"use strict";
let favouriteplaces = ["Makkah", "Hunza", "Dubai", "Qatar"];
console.log(favouriteplaces);
console.log("alphabetical order     " + [...favouriteplaces].sort() + "\n");
console.log("original order    " + favouriteplaces + "\n");
console.log("reverse alphabetical order     " + [...favouriteplaces].sort().reverse() + "\n");
console.log("original order   " + favouriteplaces + "\n");
console.log("Reverse the order of list     " + favouriteplaces.reverse() + "\n");
console.log("alphabetical order    " + favouriteplaces.sort() + "\n");
console.log("alphabetical order    " + favouriteplaces.sort().reverse() + "\n");
